name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies for CDK
        working-directory: cdk
        run: pnpm install

      - name: Install AWS CDK
        run: pnpm add -g aws-cdk

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-1"

      - name: Synth stack
        working-directory: cdk
        run: cdk synth

      - name: Deploy stack
        working-directory: cdk
        run: cdk deploy --all --require-approval never
